### ISSUE TITLE
Error running pattern selection module

### ISSUE THREAD

**Issue by shashidr** [FofanovLab/VaST#3]
Hi Tara,

I was able to run the preprocessing workflow without errors ( input files generated with NASP), but pattern selection module is giving me the following error. Appreciate any input.
Thanks,

Shashi

Command:
python VaST-1.0/VaST/pattern_selection.py --log DEBUG -t 32 TEST TEST_2019-01-14_16-12-10/ 

Traceback (most recent call last):
  File "VaST-1.0/VaST/pattern_selection.py", line 323, in <module>
    pattern_selection(PROJECT_DIR, **PARAMS)
  File "VaST-1.0/VaST/pattern_selection.py", line 111, in pattern_selection
    int(preprocessing_history.get_parameter("PZ_SIZE")))
  File "VaST-1.0/VaST/pattern_selection.py", line 23, in _get_minimum_spanning_set
    for rep, mss in enumerate(minimum_spanning_set_objs)]
  File "VaST-1.0/VaST/Minimum_Spanning_Set.py", line 91, in get_minimum_spanning_set
    self._add_pattern_to_set([next_pattern])
  File "VaST-1.0/VaST/Minimum_Spanning_Set.py", line 186, in _add_pattern_to_set
    _ambiguous_score_helper(self._current_resolution)
  File "VaST-1.0/VaST/Minimum_Spanning_Set.py", line 325, in _ambiguous_score_helper
    n_strains_in_feature_category = Counter(chain(*pattern))
  File "/local/anaconda2/envs/vast_env/lib/python2.7/collections.py", line 477, in __init__
    self.update(*args, **kwds)
  File "/local/anaconda2/envs/vast_env/lib/python2.7/collections.py", line 566, in update
    for elem in iterable:
TypeError: 'float' object is not iterable

**Comment by tfursten** [comment]
Hi @shashidr, can you try to run it again with the latest version on master and see if you have the same issue?

**Comment by shashidr** [comment]
Latest version worked fine. Thanks Tara
