### ISSUE TITLE
ValueError: could not broadcast input array from shape (0) into shape (872645)

### ISSUE THREAD

**Issue by bjarnebartlett** [FofanovLab/VaST#7]
Greetings,

When I run the following command:  
`python ./VaST-master/VaST/preprocessing.py test /media/bjarne/SSD1/Taro_Flashdrive/ /media/bjarne/SSD1/Taro_Flashdrive/Taro1.fq_var_SiteMatrix.txt --full_matrix_path /media/bjarne/SSD1/Taro_Flashdrive/Taro1.fq_full_SiteMatrix.txt`

I get the below error regarding missing strains:
```
Traceback (most recent call last):
  File "./VaST-master/VaST/preprocessing.py", line 508, in <module>
    ARGS.full_matrix_path, ARGS.flag_file_path, **PARAMS)
  File "./VaST-master/VaST/preprocessing.py", line 337, in preprocessing
    history, project_directory, **args)
  File "./VaST-master/VaST/preprocessing.py", line 224, in get_flags_from_matrix
    flag_file)
  File "./VaST-master/VaST/preprocessing.py", line 208, in _get_nonconserved_counts
    "Flag": flags}, columns=['Site', "Genome", "Flag"])
  File "/home/bjarne/anaconda3/envs/vast_env/lib/python2.7/site-packages/pandas/core/frame.py", line 275, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/bjarne/anaconda3/envs/vast_env/lib/python2.7/site-packages/pandas/core/frame.py", line 411, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/bjarne/anaconda3/envs/vast_env/lib/python2.7/site-packages/pandas/core/frame.py", line 5506, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/home/bjarne/anaconda3/envs/vast_env/lib/python2.7/site-packages/pandas/core/internals.py", line 4314, in create_block_manager_from_arrays
    construction_error(len(arrays), arrays[0].shape, axes, e)
  File "/home/bjarne/anaconda3/envs/vast_env/lib/python2.7/site-packages/pandas/core/internals.py", line 4276, in construction_error
    raise e
ValueError: could not broadcast input array from shape (0) into shape (872645)
```
Could this be because I am running a test on a single strain? Are my matrix files missing a column perhaps? I am new to this software and would appreciate any insight on this, my VCF and site matrix files are attached below. 

Aloha. 

-Bjarne

[Taro1.fq_var.vcf.gz](https://github.com/FofanovLab/VaST/files/6737319/Taro1.fq_var.vcf.gz)
[Taro1.fq_full.vcf.gz](https://github.com/FofanovLab/VaST/files/6737320/Taro1.fq_full.vcf.gz)
[Taro1.fq_full_SiteMatrix.txt](https://github.com/FofanovLab/VaST/files/6737315/Taro1.fq_full_SiteMatrix.txt)
[Taro1.fq_var_SiteMatrix.txt](https://github.com/FofanovLab/VaST/files/6737316/Taro1.fq_var_SiteMatrix.txt)

**Comment by bjarnebartlett** [comment]
Updated Site Matrix Files attached. Written with a command similar to the following: 
`bcftools query -f '%CHROM::%POS::%POS\n' ${sample}_var.vcf.gz > ${sample}_var_SiteMatrix.txt
`
[Taro1.fq_var_SiteMatrix.txt](https://github.com/FofanovLab/VaST/files/6737358/Taro1.fq_var_SiteMatrix.txt)
